### ISSUE TITLE
inline function ‘cpu’ declared but never defined

### ISSUE THREAD

**Issue by ghost** [chillancezen/ZeldaOS.x86_64#1]
I have faced issue below:
sh# make
[CC] x86_64/processor_local_storage.c
In file included from x86_64/processor_local_storage.c:9:0:
./x86_64/include/lapic.h:87:17: error: inline function ‘cpu’ declared but never defined [-Werror]

**Comment by ghost** [comment]
I've fixed it with change inline cpu() to extern cpu() in ./x86_64/include/lapic.h and ./x86_64/lapic.c. Because this function is called as external linkage.

**Comment by chillancezen** [comment]
Thanks for issue, This is an ongoing project for study use,  a lot of Intel CPU features are interesting me, that's why I filed this project to give a try. you can run the project with  `KVM='--enable-kvm --cpu host' ZELDA64=/path/to/repo make run` , recently I am trying vmx

**Comment by ghost** [comment]
This repo is really good to learn OS dev (MP, VMX initilization). I will write new features to this (task scheduling, Virtualization current state of OS etc.).

Thank you!

**Comment by chillancezen** [comment]
you are welcome to do this.
we can discuss and learn from all of it.!
