### ISSUE TITLE
QEMU TCG doesn't support VMX

### ISSUE THREAD

**Issue by ghost** [chillancezen/ZeldaOS.x86_64#2]
ZeldaOS is used QEMU TCG as accelerator but TCG doesn't support VMX. That's why I've changed accelerator as enable-kvm.
Issue for TCG:
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]

Command line:
qemu-system-x86_64 -enable-kvm -cpu host,-kvm_pv_eoi,-kvm_steal_time,-kvm_asyncpf,-kvmclock,+vmx -drive file=Zelda64.img,if=ide -smp 4 -m 1024 -serial stdio -monitor null -nographic

**Comment by chillancezen** [comment]
please find a linux host with vt-x enabled in bios. `cat /proc/cpuinfo|grep vmx`, and enable nested virtualization: 
```
#/etc/modprobe.d/kvm-nested.conf
options kvm-intel nested=1
options kvm-intel enable_shadow_vmcs=1
options kvm-intel enable_apicv=1
options kvm-intel ept=1
// and then reload these two modules: kvm and kvm_intel.
``` 

if you don not want to run any vmx related features, do not specify any options related to kvm, my kernel will avoid running them when it does not detect vmx feature.  please refer to the command in top level makefile.

**Comment by chillancezen** [comment]
note the hypervisor is incomplete, nothing to play with at all.

**Comment by ghost** [comment]
This problem is related to accelerator, I don't need any of VMX features (shadow vmcs, apic emulation). I've solved this problem with KVM variable. Thank you!
