### ISSUE TITLE
Settings for Guest HLT bitmap

### ISSUE THREAD

**Issue by ghost** [chillancezen/ZeldaOS.x86_64#3]
I've configured CPU_BASED_VM_EXEC_CONTROL bitmap for handling hlt instruction to exit to host state. But it didn't worked correctly. I expected interrupt handler when executing vm_exit_handler procedure. Do you have any idea about that?
```

.section .text
.code64

.global vm_exit_handler
.global halting


halting:
	hlt


vm_exit_handler:

    int $0x45
    hlt


void trampoline(void){
    __asm__("hlt");
}


static void
initialize_vmcs_guest_state(struct vmcs_blob *vm)
{
#define _(encoding, value) {                                                   \
    ASSERT(vmx_write((encoding), (value)) == ERROR_OK);                        \
    ASSERT(vmx_read((encoding)) == (value));                                   \
}
    unsigned long val;
    val = read_msr(MSR_IA32_VMX_PROCBASED_CTLS);
    val |= CPU_BASED_HLT_EXITING;
    _(CPU_BASED_VM_EXEC_CONTROL, (uint32_t)val);
    _(GUEST_RIP, (uint64_t)&halting);

    _(VMCS_LINK_POINTER, -1UL);
#undef _
}

```

**Comment by chillancezen** [comment]
I assume that you are setting the bit to cause VM exits when guest executes hlt instruction.
I did that like this: https://github.com/chillancezen/ZeldaOS.x86_64/blob/master/vm_monitor/vmx_vmcs.c#L269

it's part of primary processor based execution control.   not guest state. 

Thanks,
Jie

**Comment by chillancezen** [comment]
oh the external interrupt can be normally delivered after vm exits and the rsp specified in host state will be used as stack to do interrupt delivery I assume. I will investigate on this later

**Comment by ghost** [comment]
I know i've configured this way (with 0x00004002 encoding flag for primary based execution control). But vm_exithandler didn't executed correctly. I think, I need a vmx monitor for error tracing.

**Comment by ghost** [comment]
BTW Bochs VMX support has handling of VMFAILs, I will use it.

[https://github.com/Stary2001/switch-bochs/blob/34612346c0505bdc64d453fc287d4f690bc59c64/cpu/vmx.cc#L730](https://github.com/Stary2001/switch-bochs/blob/34612346c0505bdc64d453fc287d4f690bc59c64/cpu/vmx.cc#L730)

**Comment by chillancezen** [comment]
that’s great!

**Comment by chillancezen** [comment]
hi Emin,
  did you ever launch A vm successfully with the VMX instructions?
  if so, could you please share your code with me?

Thanks,
Jie

**Comment by chillancezen** [comment]
finally I make it to launch a guest. 
I should never be that careless to initialize VMCS.

**Comment by ghost** [comment]
Hi, I couldn't do it. I think there is problem about VMCS structure. Did you check it?

**Comment by ghost** [comment]
I checked it. It's worked correctly. what was the problem? Can you explain it?

**Comment by chillancezen** [comment]
> I checked it. It's worked correctly. what was the problem? Can you explain it?

please see my last two commits, I did make the VMCS right. it's really exciting to see it enters vmx non-root mode and return to host.

**Comment by ghost** [comment]
How could you observed it enters to guest state? as I see after vmlaunch executing that jumps to vmexit with exit reason 0x80000021 (VM-entry failure due to invalid guest state).

**Comment by chillancezen** [comment]
> How could you observed it enters to guest state? as I see after vmlaunch executing that jumps to vmexit with exit reason 0x80000021 (VM-entry failure due to invalid guest state).

this time I do enter genuine guest vmx non-root mode, you can see the change in my last commit: https://github.com/chillancezen/ZeldaOS.x86_64/commit/1561d25d7783c66172d84dd92c15a88203fef44a

however even I copy the guest image for the guest, it always reports vm-exit with reason 0x1; not sure whether my guest code was executed. this needs more investigation.

**Comment by ghost** [comment]
That's worked very well. You will faced exit reason 0x1 (that's external interrupt) because you've configured
it in pinbased control fields.
 // External Interrupt causes a VM EXIT
 pinbased_vm_execution_ctrl |= 1;

After delete this I have occurred 0xc exit reason (hlt instruction).

**Comment by chillancezen** [comment]
> That's worked very well. You will faced exit reason 0x1 (that's external interrupt) because you've configured
> it in pinbased control fields.
> // External Interrupt causes a VM EXIT
> pinbased_vm_execution_ctrl |= 1;
> 
> After delete this I have occurred 0xc exit reason (hlt instruction).

you advice is helpful,  after I comment the pin based control for external interrupt, the guest code gets executed. 

even though the guest CPU has external interrupt masked(the IF is reset), it does not prevent external interrupt from being delivered.  during my kernel init phase, I configure lapic timer, which is taken as external interrupt. I guess the external interrupt is always prioritized.

**Comment by ghost** [comment]
Hi, I have faced issue about STI instruction. When executed STI instruction in non-root mode (guest state) after that other instruction didn't resume. Do you have any idea about this?

**Comment by ghost** [comment]
I've found solution. After STI execution, VMM exits with I/O reason.

**Comment by chillancezen** [comment]
oh I did not notice that STI can cause an IO vmexit.
 but I encounter the vm entry failure when I inject an interrupt event after guest os issues sti（IF will be set.）.  I did not find any thing useful from intel sdm either

**Comment by ghost** [comment]
Nope, it's my fault. I filled out all of memory region with 90. That's why stack/other regions were dirty and it was interfere to instruction execution (may be rflags).

**Comment by chillancezen** [comment]
I am closing this, as I can foresee for now,  I will not touch this project any more.
