### ISSUE TITLE
FEATURE Control MSR lock flag

### ISSUE THREAD

**Issue by ghost** [chillancezen/ZeldaOS.x86_64#6]
Hi Jie, When I was trying boot to bare metal machine with PXE, But I got issue "!(eax & VMXON_LOCK_FLAG) failed". According to Intel manual Feature control msr lock flag is cleared when logical processor is reset. 

`VMXON is also controlled by the IA32_FEATURE_CONTROL MSR (MSR address 3AH). This MSR is cleared to zero when a logical processor is reset. ... Bit 0 is the lock bit. If this bit is clear, VMXON causes a general-protection exception. If the lock bit is set, WRMSR to this MSR causes a general-protection exception; the MSR cannot be modified until a power-up reset condition. System BIOS can use this bit to provide a setup option for BIOS to disable support for VMX. To enable VMX support in a platform, BIOS must set bit 1, bit 2, or both (see below), as well as the lock bit.
`
I wonder is it firmware depended issue?

Full log:
```
[info] vm_monitor/vmx_misc.c:37 cpu feature:vmx supported
[info] vm_monitor/vmx_misc.c:67 EAX LOCK 5
[assert] vm_monitor/vmx_misc.c:72 !(eax & VMXON_LOCK_FLAG) failed
[info] x86_64/panic.c:71 cpu:0, idt.base:0x257000 idt.size:0xfff
[info] x86_64/panic.c:73 tr:0x450028, gdt.base:0x211038 gdt.size:0x427
[info] x86_64/panic.c:75 fs.base:0x0, gs.base:0x0 efer:0x500
[info] x86_64/panic.c:77 cr4:0x20, cr3:0x845c000, cr2:0x0, cr0:0x80000011
[info] x86_64/panic.c:110     frame #0 <205106>
[info] x86_64/panic.c:110     frame #1 <20657e>
[info] x86_64/panic.c:110     frame #2 <20069e>
[info] x86_64/panic.c:110     frame #3 <20086f>
[info] x86_64/panic.c:110     frame #4 <200044>


```

![Capture](https://user-images.githubusercontent.com/14012405/62691922-bb6ff400-b9e0-11e9-9019-816c6c9f9ce8.PNG)

BTW: I've loaded kernel successfully to bare metal machine with PXE :).

**Comment by chillancezen** [comment]
hi Emin, 
for the VMXON_LOCK_FLAG, seem once it been set, it will not be reset until next poweron.
have you tried to enable virtualization support in BIOS setup?

and It's great to hear that this little kernel can be booted via PXE. I will try that too. 
could you give me some guidance on how to boot that ? I only try ESXi PXE boot, it will never fit my kernel.

thanks,
Jie

**Comment by ghost** [comment]
Yes you can boot max 32 kb (bootloader) in first stage with PXE. I wrote PXE based bootloader that download kernel from TFTP () and load it to memory. I will share codes after few works.

**Comment by ghost** [comment]
Hi Jie, I tested kernel on the ThinkPad and I got same issue. At the vm_monitor_init stage IA32_FEATURE_CONTROL_MSR field is 0x5 and VMX lock flag is enabled. Also Virtualization is enabled in BIOS.

![photo_2019-08-10_13-24-56](https://user-images.githubusercontent.com/14012405/62820230-4fbd9080-bb72-11e9-8b5a-7e684838960d.jpg)
![photo_2019-08-10_13-24-50](https://user-images.githubusercontent.com/14012405/62820231-50562700-bb72-11e9-8848-d2b8e67168cc.jpg)

**Comment by chillancezen** [comment]
hi Emin,
   the https://github.com/chillancezen/ZeldaOS.x86_64/commit/72f7684d8e368a1c7e7407c135c039eb0c9c9925 is supposed to fix the issue. 


 EAX is already 5, it means VMXON is already enabled by some code, I guess BIOS code did that, in such case, I should do not enable it one more time.

thanks
Jie
