### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by sskras** [chillancezen/ZeldaOS.x86_64#8]
"Copyright" strings are present in the source, but I found no project's License.
For those interested to reuse your code, it would be nice to have it present.

In the case you have not decided which one to choose yet and should you like permissive approach (vs copyleft one), I offer you to consider the `Blue Oak Model License` announced by a lawyer a year ago:
https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html

Author also responds to some of the doubts here:
https://news.ycombinator.com/item?id=19347797

**Comment by chillancezen** [comment]
I got a license here: https://github.com/chillancezen/ZeldaOS.x86_64/blob/master/LICENSE thanks.

**Comment by sskras** [comment]
Let's close the issue then:)
